### ISSUE TITLE
[Config] 관련 질문드립니다!

### ISSUE THREAD

**Issue by chokyungjin** [Moop-App/Moop-iOS#64]
이런 질문으로 이슈로 올려 죄송합니다!! 제가 지금 학생인데 영화 관련 iOS 앱을 제작하고 있습니다! 그러다 우연히 Moop이란 앱을 보았고 정말 많은 도움을 받을것 같다고 생각합니다! 그런데 Config 관련된 파일이 없어서 빌드를 실행하지 못하고 있습니다! 정말 개인적으로 혼자서 공부하고 열심히 혼자 코드리뷰를 진행하고 싶습니다. chokj1472@gmail.com로 답변 남겨주시면 정말 감사드리겠습니다!

**Comment by kor45cw** [comment]
@chokyungjin 안녕하세요 서비스를 위해 별도의 API는 제공되고 있지 않으며,
디버깅을 원하신다면, API.baseURL로 
`MOOP_API_BASE_URL = "https://moop-public-api.firebaseio.com/alpha/"`
를 사용하시면 될것 같습니다~!
